{"name": "Проверка появления ошибки при заполнении невалидного логина/пароля и возвращения правильного код ответа", "status": "passed", "attachments": [{"name": "stdout", "source": "f1b9e407-c572-4fc3-9dde-8bf3fdcb0043-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "login", "value": "'yytr'"}, {"name": "password", "value": "['kdschdvwvu', 'xzlvfqbwcx', 'dtsuckobzw']"}], "start": 1706799476612, "stop": 1706799476888, "uuid": "f06d040a-4482-4648-a3aa-8c6ee9034d40", "historyId": "901f839d61cf5a8df031a9e016878f29", "testCaseId": "1948f0443281776f830c6ca14962e75a", "fullName": "tests.test_courier_auth.TestAuth#test_return_error_message_with_invalid_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_auth"}, {"name": "subSuite", "value": "TestAuth"}, {"name": "host", "value": "MacBook-Air-Kamilla.local"}, {"name": "thread", "value": "30509-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_auth"}]}