{"name": "Проверка появления ошибки при заполнении невалидного логина/пароля и возвращения правильного код ответа", "status": "passed", "attachments": [{"name": "stdout", "source": "709c46a9-05fe-4a6f-8614-b3a1d892a688-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "login", "value": "['wnjjkfozum', 'kgvykonira', 'ibocjmkmpu']"}, {"name": "password", "value": "['pfcryhurwf', 'fbzpafcobv', 'yndwgdjuwh']"}], "start": 1706729779273, "stop": 1706729779615, "uuid": "476dc314-2f9d-467d-9d4b-07f4acc3b2c2", "historyId": "055761d41afe92e54f10df9e07d1d0e0", "testCaseId": "1948f0443281776f830c6ca14962e75a", "fullName": "tests.test_courier_auth.TestAuth#test_return_error_message_with_invalid_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_auth"}, {"name": "subSuite", "value": "TestAuth"}, {"name": "host", "value": "MacBook-Air-Kamilla.local"}, {"name": "thread", "value": "14573-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_auth"}]}