{"name": "Проверка появления ошибки при заполнении невалидного логина/пароля и возвращения правильного код ответа", "status": "passed", "attachments": [{"name": "stdout", "source": "46a93c6b-a8f3-4643-b15f-dff3bf3b4375-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "login", "value": "['bavoqlncnk', 'ugrembszym', 'cnbmookyuk']"}, {"name": "password", "value": "['jlupysdgxo', 'uylvanmheb', 'llynmcancp']"}], "start": 1706799477218, "stop": 1706799477527, "uuid": "7966171c-8ec8-443f-882e-f10361b2b204", "historyId": "de1ab4d827a48022865a9ae9b74d9096", "testCaseId": "1948f0443281776f830c6ca14962e75a", "fullName": "tests.test_courier_auth.TestAuth#test_return_error_message_with_invalid_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_auth"}, {"name": "subSuite", "value": "TestAuth"}, {"name": "host", "value": "MacBook-Air-Kamilla.local"}, {"name": "thread", "value": "30509-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_auth"}]}